source "https://rubygems.org"

# Jekyll version that GitHub Pages uses
gem "jekyll", "~> 3.9.3"

# Just the Docs theme
gem "just-the-docs"

# Required for GitHub Pages compatibility
gem "github-pages", group: :jekyll_plugins

# Required for Ruby 3.0+
gem "webrick", "~> 1.8"

# Plugins
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end

# Windows and JRuby does not include zoneinfo files
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
